version: '{build}'

branches:
  only:
  - master
  - vNext

skip_tags: true

clone_folder: C:\projects\libgit2sharp

environment:
  matrix:
  - xunit_runner: xunit.console.exe
    Arch: 64
  - xunit_runner: xunit.console.x86.exe
    Arch: 32

build_script:
- nuget restore "C:\projects\libgit2sharp\LibGit2Sharp.sln"
- msbuild "C:\projects\libgit2sharp\LibGit2Sharp.sln" /verbosity:normal /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /property:ExtraDefine="LEAKS_IDENTIFYING"

test_script:
- '"C:\projects\libgit2sharp\packages\xunit.runners.2.0.0-beta5-build2785\tools\%xunit_runner%"  "C:\projects\libgit2sharp\LibGit2Sharp.Tests\bin\Release\LibGit2Sharp.Tests.dll"'
- IF %ERRORLEVEL% NEQ 0 EXIT /B %ERRORLEVEL%

notifications:
- provider: Email
  to:
    - emeric.fermas@gmail.com
  on_build_status_changed: true
